### ISSUE TITLE
Compile in windows

### ISSUE THREAD

**Issue by hcoiro** [rnascunha/pusha#1]
Hi. I am trying to test this tool in windows. Making the build I have the error below:
It is missing the  'unistd.h' <- I can solve this  adding  this https://github.com/robinrowe/libunistd as library , and I can compile  "vapid.c".

When doing the cmake --build . I have several erros,  ( following the first part) with the file "debug.c'
Did you compile this in Windows without problem?

***** debug.c error****
 debug.c
F:\Pythondev\libunistd\unistd\gettimeofday.h(15,53): warning C4115: 'timezone': definición de tipo con nombre entre par
éntesis [F:\Pythondev\pusha\build\pusha.vcxproj]
F:\Pythondev\pusha\src\debug.c(225,27): error C2059: error de sintaxis: '}' [F:\Pythondev\pusha\build\pusha.vcxproj]
F:\Pythondev\pusha\src\debug.c(230,55): error C2065: 'result': identificador no declarado [F:\Pythondev\pusha\build\pus
ha.vcxproj]
F:\Pythondev\pusha\src\debug.c(230,55): error C4047: 'función': 'PADDRINFOA *' es distinto en los niveles de direcciona
miento indirecto de 'int *' [F:\Pythondev\pusha\build\pusha.vcxproj]

*****log compiling Windows****
F:\Pythondev\pusha\build> cmake ..
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22000.
-- The C compiler identification is MSVC 19.31.31107.0
-- The CXX compiler identification is MSVC 19.31.31107.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.31.31103/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.31.31103/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenSSL: C:/ProgramData/Anaconda3/Library/lib/libcrypto.lib (found suitable version "1.1.1d", minimum required is "1.1.0")
-- MSVC build
-- Configuring done
-- Generating done
-- Build files have been written to: F:/Pythondev/pusha/build

F:\Pythondev\pusha\build> cmake --build .
Microsoft (R) Build Engine versión 17.1.0+ae57d105c para .NET Framework
Copyright (C) Microsoft Corporation. Todos los derechos reservados.

  Checking Build System
  Building Custom Rule F:/Pythondev/pusha/third/ecec/CMakeLists.txt
  base64url.c
  encrypt.c
  decrypt.c
  keys.c
  params.c
  trailer.c
  Generando código...
  ece.vcxproj -> F:\Pythondev\pusha\build\third\ecec\Debug\ece.lib
  Building Custom Rule F:/Pythondev/pusha/CMakeLists.txt
  vapid.c
F:\Pythondev\pusha\src\vapid.c(3,10): fatal error C1083: No se puede abrir el archivo incluir: 'unistd.h': No such file
 or directory [F:\Pythondev\pusha\build\pusha.vcxproj]
  web_push.c
F:\Pythondev\pusha\src\web_push.c(174,9): warning C4101: 'size': variable local sin referencia [F:\Pythondev\pusha\buil
d\pusha.vcxproj]
  http.c
F:\Pythondev\pusha\src\http.c(118,45): warning C4267: 'función': conversión de 'size_t' a 'unsigned int'; posible pérdi
da de datos [F:\Pythondev\pusha\build\pusha.vcxproj]
F:\Pythondev\pusha\src\http.c(219,15): warning C4100: 'cypher_payload': parámetro formal sin referencia [F:\Pythondev\p
usha\build\pusha.vcxproj]
  debug.c
F:\Pythondev\pusha\src\debug.c(6,10): fatal error C1083: No se puede abrir el archivo incluir: 'unistd.h': No such file
 or directory [F:\Pythondev\pusha\build\pusha.vcxproj]
  helper.c
  pusha.c
  Generando código...

F:\Pythondev\pusha\build>

**Comment by rnascunha** [comment]
Hi @hcoiro, are you using the `win-port` branch? At the project directory, use:

```
git checkout win-port
```

Rafael

**Comment by hcoiro** [comment]
Great thanks.  I didn´t see the win-port version. Now it compile.
I will test this, my main idea is evaluate if it is possible to port to arduino.
Thanks again

**Comment by rnascunha** [comment]
@hcoiro , I just merged the `win-port` branch to `master`.

About the port to Arduino, the library highly depends on OpenSSL. If it's available, I see no problem.

Any difficulty feel free to reach me.

Rafael

**Comment by hcoiro** [comment]
@rnascunha Thanks Rafael. It is working in windows. I subscribe with Chrome and I am receiving the notification.
How do you have to write the payload if wanted to show "Title" and "body", because writing  the option -m 'Notification message' I can not see the message on the notification.

**Comment by rnascunha** [comment]
@hcoiro , check this page: https://web.dev/push-notifications-handling-messages/

You must send everything at the payload (like a JSON for example), receive it at the service worker `push` event, parse the `event.data` object, construct and show the notification.

**Comment by hcoiro** [comment]
@rnascunha Thanks  with the document above I figured out that the payload to send in order to evaluate as JSON in chrome browser is the following: "{\"title\": \"Hey, this is a push notification!\", \"body\": \"Message body\"}"
Thanks
